<a href="https://colab.research.google.com/github/anton-gavrilin/colab_google/blob/main/classification_ann_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial neural network to classify flowers into three classes 
Examples of flowers classes: (Iris-setosa, Iris-versicolor, Iris-virginica).

Load significant libraries

In [2]:
# Load libraries
import pandas as pd
import numpy
import random
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

Load data and designate column names

In [3]:
# Load dataset
filename = 'iris.data'
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = pd.read_csv(filename, names=names)

Display how looks dataset with grouping flowers where every flower have 50 data rows

In [4]:
print(dataset)
print(dataset.head())

# class distribution
print(dataset.groupby('class').size())

     sepal-length  sepal-width  petal-length  petal-width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]
   sepal-length  sepal-width  petal-length  petal-width        class
0           5.1    

Create sequance of layers that have: First layer specify number of input attributes; second layer use rectified linear unit for outputing small and large values; third layer or output layer has 3 nodes and uses the softmax activation function(outputs a 0 for all options and 1 for the chosen option)

In [5]:
model = Sequential([
    Dense(64, input_shape=(4,), kernel_initializer="random_uniform", activation='relu'),
    Dense(32, activation='relu'),
    Dense(3, activation='softmax')
])

Compile the model with sparse_categorical_crossentropy function - for multiclass logarithmic loss

In [6]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

* X is data without class column
* Y is data of class column
* Class is column that defines which flower of iris is it.
Split data to train(2/3) and test(1/3)

In [29]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

Y = numpy.unique(y, return_inverse=True)[1]

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=7)

Training over 50 epochs, and each epoch is split into 8 batches.

In [9]:
epochs = 50
batch_size = 8
model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size)

Epoch 1/50
13/13 [==============================] - 0s 2ms/step - loss: 0.0777 - accuracy: 0.9700
Epoch 2/50
13/13 [==============================] - 0s 3ms/step - loss: 0.0731 - accuracy: 0.9700
Epoch 3/50
13/13 [==============================] - 0s 2ms/step - loss: 0.0810 - accuracy: 0.9700
Epoch 4/50
13/13 [==============================] - 0s 2ms/step - loss: 0.0707 - accuracy: 0.9800
Epoch 5/50
13/13 [==============================] - 0s 3ms/step - loss: 0.0770 - accuracy: 0.9700
Epoch 6/50
13/13 [==============================] - 0s 8ms/step - loss: 0.0761 - accuracy: 0.9800
Epoch 7/50
13/13 [==============================] - 0s 7ms/step - loss: 0.0658 - accuracy: 0.9700
Epoch 8/50
13/13 [==============================] - 0s 3ms/step - loss: 0.0680 - accuracy: 0.9800
Epoch 9/50
13/13 [==============================] - 0s 3ms/step - loss: 0.0652 - accuracy: 0.9800
Epoch 10/50
13/13 [==============================] - 0s 4ms/step - loss: 0.0634 - accuracy: 0.9800
Epoch 11/50
13/13 [

In [10]:
# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f'Test loss: {loss:.3f}')
print(f'Test accuracy: {accuracy:.3f}')

Test loss: 0.076
Test accuracy: 0.960


Take some random 5 inputs of existed data and put it to model to predict correct answer

In [27]:
def get_name_by_num(num):
    return "Iris-setosa" if num == 0 else "Iris-versicolor" if num == 1 else "Iris-virginica"

random_inputs = [random.randint(0, 150) for _ in range(5)]
inputs_data = [X[i].tolist() for i in random_inputs]
predictions = (model.predict(inputs_data) > 0.5).astype(int)

# summarize the first 5 cases
for i in random_inputs:
    predicted_index = random_inputs.index(i)
    true_index = numpy.where(predictions[predicted_index] == 1)[0][0]
    predicted = get_name_by_num(true_index)
    expected = get_name_by_num(Y[i])
    print(f'{X[i]} => {predicted} (expected -> {expected})')

1/1 [==============================] - 0s 39ms/step
[6.1 2.8 4.7 1.2] => Iris-versicolor (expected -> Iris-versicolor)
[6.  3.  4.8 1.8] => Iris-virginica (expected -> Iris-virginica)
[6.6 2.9 4.6 1.3] => Iris-versicolor (expected -> Iris-versicolor)
[6.7 3.3 5.7 2.5] => Iris-virginica (expected -> Iris-virginica)
[7.7 3.8 6.7 2.2] => Iris-virginica (expected -> Iris-virginica)


In [31]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 64)                320       
                                                                 
 dense_4 (Dense)             (None, 32)                2080      
                                                                 
 dense_5 (Dense)             (None, 3)                 99        
                                                                 
Total params: 2,499
Trainable params: 2,499
Non-trainable params: 0
_________________________________________________________________


In [32]:
print(model.get_config())

{'name': 'sequential_1', 'layers': [{'class_name': 'InputLayer', 'config': {'batch_input_shape': (None, 4), 'dtype': 'float32', 'sparse': False, 'ragged': False, 'name': 'dense_3_input'}}, {'class_name': 'Dense', 'config': {'name': 'dense_3', 'trainable': True, 'dtype': 'float32', 'batch_input_shape': (None, 4), 'units': 64, 'activation': 'relu', 'use_bias': True, 'kernel_initializer': {'class_name': 'RandomUniform', 'config': {'minval': -0.05, 'maxval': 0.05, 'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}}, {'class_name': 'Dense', 'config': {'name': 'dense_4', 'trainable': True, 'dtype': 'float32', 'units': 32, 'activation': 'relu', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_re